// Implementation file for class: country
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "country.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
country::country()
{
  // Things to do in the constructor
}

// DTOR for class
country::~country()
{
  // Things to do in the destructor
}

