// Interface definition file for class: Animal
// Automatically generated by: CX-Hibernate
// File: Animal.h
//
#pragma once
#include <CXObject.h>
#include <bcd.h>
#include <SQLDate.h>
#include <SQLTime.h>
#include <SQLTimestamp.h>
#include <SQLInterval.h>
#include <SQLGuid.h>
#include <SQLVariant.h>

class Animal : public CXObject
{
public:
  // CTOR of an CXObject derived class
  Animal();
  // DTOR of an CXObject derived class
  virtual ~Animal();

  // Serialization of our persistent objects
  DECLARE_CXO_SERIALIZATION;

  // GETTERS
  int        GetId()              { return m_id;                };
  CString    GetAnimalName()      { return m_animalName;        };
  bool       GetHas_claws()       { return m_has_claws;         };
  bool       GetHas_hair()        { return m_has_hair;          };
  bool       GetHas_wings()       { return m_has_wings;         };
  int        GetNumberOfLegs()    { return m_numberOfLegs;      };
  CString    GetDiscriminator()   { return m_discriminator;     };

protected:
  // Database persistent attributes
  int        m_id                 { 0 };
  CString    m_animalName        ;
  bool       m_has_claws          { false };
  bool       m_has_hair           { false };
  bool       m_has_wings          { false };
  int        m_numberOfLegs       { 0 };
  CString    m_discriminator     ;

private:
  // Transient attributes go here
};
