// Interface definition file for class: Animal
// Automatically generated by: CX-Hibernate
// File: Animal.h
//
#pragma once
#include <CXObject.h>
#include <bcd.h>
#include <SQLDate.h>
#include <SQLTime.h>
#include <SQLTimestamp.h>
#include <SQLInterval.h>
#include <SQLGuid.h>
#include <SQLVariant.h>

class Animal : public CXObject
{
public:
  // CTOR of an CXObject derived class
  Animal();
  // DTOR of an CXObject derived class
  virtual ~Animal();

  // Serialization of our persistent objects
  DECLARE_CXO_SERIALIZATION;

  // GETTERS
  int        GetId()              { return m_id;                };
  CString    GetAnimalName()      { return m_animalName;        };
  bool       GetHas_claws()       { return m_has_claws;         };
  bool       GetHas_hair()        { return m_has_hair;          };
  bool       GetHas_wings()       { return m_has_wings;         };
  int        GetNumberOfLegs()    { return m_numberOfLegs;      };

  // SETTERS
  void       SetAnimalName(CString p_animalName) { m_animalName   = p_animalName; };
  void       SetHas_claws(bool p_has_claws)      { m_has_claws    = p_has_claws;  };
  void       SetHas_hair(bool p_has_hair)        { m_has_hair     = p_has_hair;   };
  void       SetHas_wings(bool p_has_wings)      { m_has_wings    = p_has_wings;  };
  void       SetNumberOfLegs(int p_numberOfLegs) { m_numberOfLegs = p_numberOfLegs; };

protected:
  // Database persistent attributes
  int        m_id                 { 0 };
  CString    m_animalName        ;
  bool       m_has_claws          { false };
  bool       m_has_hair           { false };
  bool       m_has_wings          { false };
  int        m_numberOfLegs       { 0 };

private:
  // Transient attributes go here
};
