// Implementation file for class: Cat
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "Cat.h"
#include "Animal.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
Cat::Cat()
{
  // Things to do in the constructor
}

// DTOR for class
Cat::~Cat()
{
  // Things to do in the destructor
}

