// (De-)Serializing factories for class: Cat
// Generated by CX-Hibernate cfg2cpp tool
// 
#include "stdafx.h"
#include "Cat.h"
#include <SQLRecord.h>
#include <SOAPMessage.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

BEGIN_XML_SERIALIZE(Cat,Animal)
  CXO_XML_SERIALIZE(m_color           ,_T("color"));
  CXO_XML_SERIALIZE(m_catdoor         ,_T("catdoor"));
  CXO_XML_SERIALIZE(m_likesWhiskas    ,_T("likesWhiskas"));
END_XML_SERIALIZE

BEGIN_XML_DESERIALIZE(Cat,Animal)
  CXO_XML_DESERIALIZE(m_color         ,_T("color"));
  CXO_XML_DESERIALIZE(m_catdoor       ,_T("catdoor"));
  CXO_XML_DESERIALIZE(m_likesWhiskas  ,_T("likesWhiskas"));
END_XML_DESERIALIZE

BEGIN_DBS_SERIALIZE(Cat,Animal)
  CXO_DBS_SERIALIZE(m_color           ,_T("color"));
  CXO_DBS_SERIALIZE(m_catdoor         ,_T("catdoor"));
  CXO_DBS_SERIALIZE(m_likesWhiskas    ,_T("likesWhiskas"));
END_DBS_SERIALIZE

BEGIN_DBS_DESERIALIZE(Cat,Animal)
  CXO_DBS_DESERIALIZE(m_color         ,_T("color"));
  CXO_DBS_DESERIALIZE(m_catdoor       ,_T("catdoor"));
  CXO_DBS_DESERIALIZE(m_likesWhiskas  ,_T("likesWhiskas"));
END_DBS_DESERIALIZE

BEGIN_DESERIALIZE_GENERATOR(Cat)
  CXO_DBS_DESERIALIZE(m_id,_T("id"));
END_DESERIALIZE_GENERATOR

// Static factory to create a new object if this class
DEFINE_CXO_FACTORY(Cat);

