// (De-)Serializing factories for class: Cat
// Generated by CX-Hibernate cfg2cpp tool
// 
#include "stdafx.h"
#include "Cat.h"
#include <SQLRecord.h>
#include <SOAPMessage.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

BEGIN_XML_SERIALIZE(Cat,Animal)
  CXO_XML_SERIALIZE(CString     ,m_color           ,"color"           ,XDT_String);
  CXO_XML_SERIALIZE(bool        ,m_catdoor         ,"catdoor"         ,XDT_Boolean);
  CXO_XML_SERIALIZE(bool        ,m_likesWhiskas    ,"likesWhiskas"    ,XDT_Boolean);
END_XML_SERIALIZE

BEGIN_XML_DESERIALIZE(Cat,Animal)
  CXO_XML_DESERIALIZE(CString     ,m_color           ,"color"           ,XDT_String);
  CXO_XML_DESERIALIZE(bool        ,m_catdoor         ,"catdoor"         ,XDT_Boolean);
  CXO_XML_DESERIALIZE(bool        ,m_likesWhiskas    ,"likesWhiskas"    ,XDT_Boolean);
END_XML_DESERIALIZE

BEGIN_DBS_SERIALIZE(Cat,Animal)
  CXO_DBS_SERIALIZE(CString     ,m_color           ,"color"           ,XDT_String);
  CXO_DBS_SERIALIZE(bool        ,m_catdoor         ,"catdoor"         ,XDT_Boolean);
  CXO_DBS_SERIALIZE(bool        ,m_likesWhiskas    ,"likesWhiskas"    ,XDT_Boolean);
END_DBS_SERIALIZE

BEGIN_DBS_DESERIALIZE(Cat,Animal)
  CXO_DBS_DESERIALIZE(CString     ,m_color           ,"color"           ,XDT_String);
  CXO_DBS_DESERIALIZE(bool        ,m_catdoor         ,"catdoor"         ,XDT_Boolean);
  CXO_DBS_DESERIALIZE(bool        ,m_likesWhiskas    ,"likesWhiskas"    ,XDT_Boolean);
END_DBS_DESERIALIZE

// Static factory to create a new object if this class
DEFINE_CXO_FACTORY(Cat);

