// Implementation file for class: Dog
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "Dog.h"
#include "Animal.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
Dog::Dog()
{
  // Things to do in the constructor
}

// DTOR for class
Dog::~Dog()
{
  // Things to do in the destructor
}

