// (De-)Serializing factories for class: Dog
// Generated by CX-Hibernate cfg2cpp tool
// 
#include "stdafx.h"
#include "Dog.h"
#include <SQLRecord.h>
#include <SOAPMessage.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

BEGIN_XML_SERIALIZE(Dog,Animal)
  CXO_XML_SERIALIZE(CString     ,m_subrace         ,"subrace"         ,XDT_String);
  CXO_XML_SERIALIZE(int         ,m_walksPerDay     ,"walksPerDay"     ,XDT_Integer);
  CXO_XML_SERIALIZE(bool        ,m_hunting         ,"hunting"         ,XDT_Boolean);
  CXO_XML_SERIALIZE(bool        ,m_waterdog        ,"waterdog"        ,XDT_Boolean);
END_XML_SERIALIZE

BEGIN_XML_DESERIALIZE(Dog,Animal)
  CXO_XML_DESERIALIZE(CString     ,m_subrace         ,"subrace"         ,XDT_String);
  CXO_XML_DESERIALIZE(int         ,m_walksPerDay     ,"walksPerDay"     ,XDT_Integer);
  CXO_XML_DESERIALIZE(bool        ,m_hunting         ,"hunting"         ,XDT_Boolean);
  CXO_XML_DESERIALIZE(bool        ,m_waterdog        ,"waterdog"        ,XDT_Boolean);
END_XML_DESERIALIZE

BEGIN_DBS_SERIALIZE(Dog,Animal)
  CXO_DBS_SERIALIZE(CString     ,m_subrace         ,"subrace"         ,XDT_String);
  CXO_DBS_SERIALIZE(int         ,m_walksPerDay     ,"walksPerDay"     ,XDT_Integer);
  CXO_DBS_SERIALIZE(bool        ,m_hunting         ,"hunting"         ,XDT_Boolean);
  CXO_DBS_SERIALIZE(bool        ,m_waterdog        ,"waterdog"        ,XDT_Boolean);
END_DBS_SERIALIZE

BEGIN_DBS_DESERIALIZE(Dog,Animal)
  CXO_DBS_DESERIALIZE(CString     ,m_subrace         ,"subrace"         ,XDT_String);
  CXO_DBS_DESERIALIZE(int         ,m_walksPerDay     ,"walksPerDay"     ,XDT_Integer);
  CXO_DBS_DESERIALIZE(bool        ,m_hunting         ,"hunting"         ,XDT_Boolean);
  CXO_DBS_DESERIALIZE(bool        ,m_waterdog        ,"waterdog"        ,XDT_Boolean);
END_DBS_DESERIALIZE

BEGIN_DESERIALIZE_GENERATOR(Dog)
  CXO_DBS_DESERIALIZE(long, m_id, "id", XDT_Integer);
END_DESERIALIZE_GENERATOR

// Static factory to create a new object if this class
DEFINE_CXO_FACTORY(Dog);

