// Implementation file for class: Infant
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "Infant.h"
#include "NaturalPerson.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
Infant::Infant()
{
  // Things to do in the constructor
}

// DTOR for class
Infant::~Infant()
{
  // Things to do in the destructor
}

