// (De-)Serializing factories for class: Infant
// Generated by CX-Hibernate cfg2cpp tool
// 
#include "stdafx.h"
#include "Infant.h"
#include <SQLRecord.h>
#include <SOAPMessage.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

BEGIN_XML_SERIALIZE(Infant,NaturalPerson)
  CXO_XML_SERIALIZE(m_immunisation,"immunisation");
  CXO_XML_SERIALIZE(m_complication,"complication");
  CXO_XML_SERIALIZE(m_hospital    ,"hospital");
END_XML_SERIALIZE

BEGIN_XML_DESERIALIZE(Infant,NaturalPerson)
  CXO_XML_DESERIALIZE(m_immunisation,"immunisation");
  CXO_XML_DESERIALIZE(m_complication,"complication");
  CXO_XML_DESERIALIZE(m_hospital    ,"hospital");
END_XML_DESERIALIZE

BEGIN_DBS_SERIALIZE(Infant,NaturalPerson)
  CXO_DBS_SERIALIZE(m_immunisation,"immunisation");
  CXO_DBS_SERIALIZE(m_complication,"complication");
  CXO_DBS_SERIALIZE(m_hospital    ,"hospital");
END_DBS_SERIALIZE

BEGIN_DBS_DESERIALIZE(Infant,NaturalPerson)
  CXO_DBS_DESERIALIZE(m_immunisation,"immunisation");
  CXO_DBS_DESERIALIZE(m_complication,"complication");
  CXO_DBS_DESERIALIZE(m_hospital    ,"hospital");
END_DBS_DESERIALIZE

BEGIN_DESERIALIZE_GENERATOR(Infant)
  CXO_DBS_DESERIALIZE(m_id,"id");
END_DESERIALIZE_GENERATOR

// Static factory to create a new object if this class
DEFINE_CXO_FACTORY(Infant);

