// Interface definition file for class: Infant
// Automatically generated by: CX-Hibernate
// File: Infant.h
//
#pragma once
#include <CXObject.h>
#include "NaturalPerson.h"
#include <bcd.h>
#include <SQLDate.h>
#include <SQLTime.h>
#include <SQLTimestamp.h>
#include <SQLInterval.h>
#include <SQLGuid.h>
#include <SQLVariant.h>

class Infant : public NaturalPerson
{
public:
  // CTOR of an CXObject derived class
  Infant();
  // DTOR of an CXObject derived class
  virtual ~Infant();

  // Serialization of our persistent objects
  DECLARE_CXO_SERIALIZATION;

  // GETTERS
  CString    GetImmunisation()    { return m_immunisation;      };
  CString    GetComplication()    { return m_complication;      };
  CString    GetHospital()        { return m_hospital;          };

protected:
  // Database persistent attributes
  CString    m_immunisation      ;
  CString    m_complication      ;
  CString    m_hospital          ;

private:
  // Transient attributes go here
};
