// Interface definition file for class: Kitten
// Automatically generated by: CX-Hibernate
// File: Kitten.h
//
#pragma once
#include <CXObject.h>
#include "Cat.h"
#include <bcd.h>
#include <SQLDate.h>
#include <SQLTime.h>
#include <SQLTimestamp.h>
#include <SQLInterval.h>
#include <SQLGuid.h>
#include <SQLVariant.h>

class Kitten : public Cat
{
public:
  // CTOR of an CXObject derived class
  Kitten();
  // DTOR of an CXObject derived class
  virtual ~Kitten();

  // Serialization of our persistent objects
  DECLARE_CXO_SERIALIZATION;

  // GETTERS
  CString    GetKit_color()       { return m_kit_color;         };
  bool       GetImmuun()          { return m_immuun;            };
  bool       GetInLitter()        { return m_inLitter;          };

protected:
  // Database persistent attributes
  CString    m_kit_color;
  bool       m_immuun             { false };
  bool       m_inLitter           { false };

private:
  // Transient attributes go here
};
