// Implementation file for class: Kitten
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "Kitten.h"
#include "Cat.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
Kitten::Kitten()
{
  // Things to do in the constructor
}

// DTOR for class
Kitten::~Kitten()
{
  // Things to do in the destructor
}

