// Implementation file for class: NaturalPerson
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "NaturalPerson.h"
#include "Subject.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
NaturalPerson::NaturalPerson()
{
  // Things to do in the constructor
}

// DTOR for class
NaturalPerson::~NaturalPerson()
{
  // Things to do in the destructor
}

