// (De-)Serializing factories for class: NaturalPerson
// Generated by CX-Hibernate cfg2cpp tool
// 
#include "stdafx.h"
#include "NaturalPerson.h"
#include <SQLRecord.h>
#include <SOAPMessage.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

BEGIN_XML_SERIALIZE(NaturalPerson,Subject)
  CXO_XML_SERIALIZE(CString     ,m_firstname       ,"firstname"       ,XDT_String);
  CXO_XML_SERIALIZE(SQLDate     ,m_date_of_birth   ,"date_of_birth"   ,XDT_Date);
  CXO_XML_SERIALIZE(bcd         ,m_length          ,"length"          ,XDT_Decimal);
END_XML_SERIALIZE

BEGIN_XML_DESERIALIZE(NaturalPerson,Subject)
  CXO_XML_DESERIALIZE(CString     ,m_firstname       ,"firstname"       ,XDT_String);
  CXO_XML_DESERIALIZE(SQLDate     ,m_date_of_birth   ,"date_of_birth"   ,XDT_Date);
  CXO_XML_DESERIALIZE(bcd         ,m_length          ,"length"          ,XDT_Decimal);
END_XML_DESERIALIZE

BEGIN_DBS_SERIALIZE(NaturalPerson,Subject)
  CXO_DBS_SERIALIZE(CString     ,m_firstname       ,"firstname"       ,XDT_String);
  CXO_DBS_SERIALIZE(SQLDate     ,m_date_of_birth   ,"date_of_birth"   ,XDT_Date);
  CXO_DBS_SERIALIZE(bcd         ,m_length          ,"length"          ,XDT_Decimal);
END_DBS_SERIALIZE

BEGIN_DBS_DESERIALIZE(NaturalPerson,Subject)
  CXO_DBS_DESERIALIZE(CString     ,m_firstname       ,"firstname"       ,XDT_String);
  CXO_DBS_DESERIALIZE(SQLDate     ,m_date_of_birth   ,"date_of_birth"   ,XDT_Date);
  CXO_DBS_DESERIALIZE(bcd         ,m_length          ,"length"          ,XDT_Decimal);
END_DBS_DESERIALIZE

// Static factory to create a new object if this class
DEFINE_CXO_FACTORY(NaturalPerson);

