// Interface definition file for class: Subject
// Automatically generated by: CX-Hibernate
// File: Subject.h
//
#pragma once
#include <CXObject.h>
#include <bcd.h>
#include <SQLDate.h>
#include <SQLTime.h>
#include <SQLTimestamp.h>
#include <SQLInterval.h>
#include <SQLGuid.h>
#include <SQLVariant.h>

class Subject : public CXObject
{
public:
  // CTOR of an CXObject derived class
  Subject();
  // DTOR of an CXObject derived class
  virtual ~Subject();

  // Serialization of our persistent objects
  DECLARE_CXO_SERIALIZATION;

  // GETTERS
  int        GetId()              { return m_id;                };
  CString    GetName()            { return m_name;              };
  CString    GetAdresline1()      { return m_adresline1;        };
  CString    GetAdresline2()      { return m_adresline2;        };
  int        GetAccount_id()      { return m_account_id;        };

protected:
  // Database persistent attributes
  int        m_id                 { 0 };
  CString    m_name              ;
  CString    m_adresline1        ;
  CString    m_adresline2        ;
  int        m_account_id         { 0 };

private:
  // Transient attributes go here
};
