// Implementation file for class: Subject
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "Subject.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
Subject::Subject()
{
  // Things to do in the constructor
}

// DTOR for class
Subject::~Subject()
{
  // Things to do in the destructor
}

