// Implementation file for class: Supplier
// Automatically generated by: CX-Hibernate
//
#include "stdafx.h"
#include "Supplier.h"
#include "Subject.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

// CTOR for class
Supplier::Supplier()
{
  // Things to do in the constructor
}

// DTOR for class
Supplier::~Supplier()
{
  // Things to do in the destructor
}

