// (De-)Serializing factories for class: Supplier
// Generated by CX-Hibernate cfg2cpp tool
// 
#include "stdafx.h"
#include "Supplier.h"
#include <SQLRecord.h>
#include <SOAPMessage.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

BEGIN_XML_SERIALIZE(Supplier,Subject)
  CXO_XML_SERIALIZE(CString     ,m_deliveryAddress ,"deliveryAddress" ,XDT_String);
  CXO_XML_SERIALIZE(bcd         ,m_balance         ,"balance"         ,XDT_Decimal);
  CXO_XML_SERIALIZE(bcd         ,m_open_orders     ,"open_orders"     ,XDT_Decimal);
  CXO_XML_SERIALIZE(bcd         ,m_open_billings   ,"open_billings"   ,XDT_Decimal);
END_XML_SERIALIZE

BEGIN_XML_DESERIALIZE(Supplier,Subject)
  CXO_XML_DESERIALIZE(CString     ,m_deliveryAddress ,"deliveryAddress" ,XDT_String);
  CXO_XML_DESERIALIZE(bcd         ,m_balance         ,"balance"         ,XDT_Decimal);
  CXO_XML_DESERIALIZE(bcd         ,m_open_orders     ,"open_orders"     ,XDT_Decimal);
  CXO_XML_DESERIALIZE(bcd         ,m_open_billings   ,"open_billings"   ,XDT_Decimal);
END_XML_DESERIALIZE

BEGIN_DBS_SERIALIZE(Supplier,Subject)
  CXO_DBS_SERIALIZE(CString     ,m_deliveryAddress ,"deliveryAddress" ,XDT_String);
  CXO_DBS_SERIALIZE(bcd         ,m_balance         ,"balance"         ,XDT_Decimal);
  CXO_DBS_SERIALIZE(bcd         ,m_open_orders     ,"open_orders"     ,XDT_Decimal);
  CXO_DBS_SERIALIZE(bcd         ,m_open_billings   ,"open_billings"   ,XDT_Decimal);
END_DBS_SERIALIZE

BEGIN_DBS_DESERIALIZE(Supplier,Subject)
  CXO_DBS_DESERIALIZE(CString     ,m_deliveryAddress ,"deliveryAddress" ,XDT_String);
  CXO_DBS_DESERIALIZE(bcd         ,m_balance         ,"balance"         ,XDT_Decimal);
  CXO_DBS_DESERIALIZE(bcd         ,m_open_orders     ,"open_orders"     ,XDT_Decimal);
  CXO_DBS_DESERIALIZE(bcd         ,m_open_billings   ,"open_billings"   ,XDT_Decimal);
END_DBS_DESERIALIZE

BEGIN_DESERIALIZE_GENERATOR(Supplier)
  CXO_DBS_DESERIALIZE(long, m_id, "id", XDT_Integer);
END_DESERIALIZE_GENERATOR

// Static factory to create a new object if this class
DEFINE_CXO_FACTORY(Supplier);

